kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-db-env-dev
  namespace: dev
  labels:
    name: postgres-db
    type: back-end
    app: quarkus-user-service
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres-db-env-dev/data"
